package com.codeqazone.karate.runners;

import com.intuit.karate.Results;
import com.intuit.karate.Runner;
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * This class executes all tests under the @smoke tag.
 */
class SmokeRunner {

    @Test
    void smokeTestsParallel() {
        // 1. Run tests and ensure JSON files are produced for the third-party reporter
        Results results = Runner.path("classpath:features")
                .tags("@smoke")
                .outputCucumberJson(true) // CRITICAL: Required for ReportBuilder
                .outputHtmlReport(true)    // Keeps the native report too
                .parallel(6);

        // 2. Call the report generator manually using the output path from results
        generateReport(results.getReportDir());

        // 3. Assertions
        Assertions.assertEquals(0, results.getFailCount(), results.getErrorMessages());
    }

    public static void generateReport(String karateOutputPath) {
        // Find all JSON files generated by the threads
        Collection<File> jsonFiles = FileUtils.listFiles(new File(karateOutputPath), new String[] {"json"}, true);
        List<String> jsonPaths = new ArrayList<>(jsonFiles.size());
        jsonFiles.forEach(file -> jsonPaths.add(file.getAbsolutePath()));

        // Set the output directory for the Masterthought report
        //To see report, look for the cucumber-html-reports folder inside target folder and open overview-features.html
        Configuration config = new Configuration(new File("target"), "Karate Starter Boilerplate");
        config.setBuildNumber("1.0.0");

        // Create the report
        ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
        reportBuilder.generateReports();
    }

}